// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD3rTr1VMXVLoAvV9YVZTpUdoljd4EXLcQ',
    appId: '1:180679294338:web:23113ef9ee83d50142a39b',
    messagingSenderId: '180679294338',
    projectId: 'guidee-7da46',
    authDomain: 'guidee-7da46.firebaseapp.com',
    storageBucket: 'guidee-7da46.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBWgYyvbCMFN40doOvrFcANST1jSm0axqo',
    appId: '1:180679294338:android:89ec1016198a81e842a39b',
    messagingSenderId: '180679294338',
    projectId: 'guidee-7da46',
    storageBucket: 'guidee-7da46.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAthgUltd6LjTpha4kRq7lF9bRup96SNX8',
    appId: '1:180679294338:ios:195c65a76c97591142a39b',
    messagingSenderId: '180679294338',
    projectId: 'guidee-7da46',
    storageBucket: 'guidee-7da46.appspot.com',
    iosClientId: '180679294338-508888usbfbo6pvv6e67ik83d5rieci1.apps.googleusercontent.com',
    iosBundleId: 'com.example.thakaaTourismProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAthgUltd6LjTpha4kRq7lF9bRup96SNX8',
    appId: '1:180679294338:ios:195c65a76c97591142a39b',
    messagingSenderId: '180679294338',
    projectId: 'guidee-7da46',
    storageBucket: 'guidee-7da46.appspot.com',
    iosClientId: '180679294338-508888usbfbo6pvv6e67ik83d5rieci1.apps.googleusercontent.com',
    iosBundleId: 'com.example.thakaaTourismProject',
  );
}
